force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Question__c/Form_Question__c.object-meta.xml
<CustomObject>
    <label>Form Question</label>
    <nameField>
        <displayFormat>FQ-{0000}</displayFormat>
        <label>Form Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Question__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText>New line for each options.</inlineHelpText>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Question_Response__c/Form_Question_Response__c.object-meta.xml
<CustomObject>
    <label>Form Question Response</label>
    <nameField>
        <displayFormat>FQR-{0000}</displayFormat>
        <label>Form Question Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Question_Response__c/fields/Form_Question__c.field-meta.xml
<CustomField>
    <fullName>Form_Question__c</fullName>
    <label>Form Question</label>
    <referenceTo>Form_Question__c</referenceTo>
    <relationshipLabel>Form Question Responses</relationshipLabel>
    <relationshipName>Form_Question_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Question_Response__c/fields/Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Form_Response__c</fullName>
    <label>Form Response</label>
    <referenceTo>Form_Response__c</referenceTo>
    <relationshipLabel>Form Question Responses</relationshipLabel>
    <relationshipName>Form_Question_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_Response__c/Form_Response__c.object-meta.xml
<CustomObject>
    <label>Form Response</label>
    <nameField>
        <displayFormat>FRN-{0000}</displayFormat>
        <label>Form Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Response__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Responses</relationshipLabel>
    <relationshipName>Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FormController.cls
public with sharing class FormController {
    @AuraEnabled(cacheable=true)
    public static string getFormNameById(Id formId){
        return [SELECT Id, Name FROM Form__c WHERE Id = :formId].Name;
    }

    @AuraEnabled(cacheable=true)
    public static List<Form_Question__c> getFormQuestionByFormId(Id formId){
        return [SELECT Id, Name, Question__c, Options__c FROM Form_Question__c WHERE Form__c = :formId];
    }

    @AuraEnabled
    public static Boolean submitFormResponse(Form_Response__c formResponse, List<Form_Question_Response__c> questionResponseList){
        try {
            insert formResponse;
            for (Form_Question_Response__c responseQuestion : questionResponseList) {
                responseQuestion.Form_Response__c = formResponse.Id;
            }
            insert questionResponseList;
            return true;
        } catch (Exception ex) {
            return false;
        }
    }
}